name: Build Packages

on:
  workflow_dispatch:
    inputs:
      folder:
        type: string
        description: Build app folder name
        required: true
      project:
        type: string
        description: Xcodeproj name
        required: true
      scheme:
        type: string
        description: App scheme name
        required: true
  workflow_call:
    inputs:
      folder:
        type: string
        description: Build app folder name
        required: true
      project:
        type: string
        description: Xcodeproj name
        required: true
      scheme:
        type: string
        description: App scheme name
        required: true
env:
  DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer

jobs:

  example:
    name: Run examples
    runs-on: macOS-14
    strategy:
        matrix:
          iosDestination: ['platform=iOS Simulator,OS=16.0,name=iPhone 14']
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set secret
        run: git config --global url."https://${{ secrets.ACTIONS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      
      - name: Set pipefail
        run: set -euo pipefail

      - name: Set SwiftPM Plugin config
        run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

      - name: Build iOS
        run: |
          xcodebuild clean build -project "${{ inputs.folder }}/${{ inputs.app }}.xcodeproj" -scheme "${{ inputs.scheme }}" | xcpretty && exit ${PIPESTATUS[0]}
        env:
          destination: ${{ matrix.iosDestination }}
