name: Build Packages

on:
  workflow_dispatch:
    inputs:
      path:
        type: string
        description: App xcodeproj file path
        required: true
      scheme:
        type: string
        description: App scheme name
        required: true
  workflow_call:
    inputs:
      path:
        type: string
        description: App xcodeproj file path
        required: true
      scheme:
        type: string
        description: App scheme name
        required: true
        
env:
  DEVELOPER_DIR: /Applications/Xcode_16.4.app/Contents/Developer

jobs:
  example:
    name: Run examples
    runs-on: macOS-15
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,name=iPhone 16 Pro,OS=18.1', 'platform=iOS Simulator,name=iPad Pro (12.9-inch) (6th generation),OS=18.1']
          
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SwiftPM Config
        run: |
          echo "machine github.com login oversizedev password ${{ secrets.ACTIONS_TOKEN }}" > ~/.netrc
          chmod 600 ~/.netrc
          set -euo pipefail
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES

      - name: Build iOS
        run: |
          xcodebuild clean build \
            -skipPackagePluginValidation \
            -project "${{ inputs.path }}.xcodeproj" \
            -scheme "${{ inputs.scheme }}" \
            -sdk iphonesimulator \
            -destination "${{ matrix.destination }}" | xcpretty && exit ${PIPESTATUS[0]}
