name: Release

on:
  workflow_dispatch:
  workflow_call:
      
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    secrets: inherit
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
