name: Tests

on:
  workflow_dispatch:
    inputs:
      clean_cache:
        type: boolean
        description: Clean cache before building
        required: false
        default: false
  workflow_call:
    inputs:
      clean_cache:
        type: boolean
        description: Clean cache before building
        required: false
        default: false
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  test:
    name: Tests
    runs-on: macOS-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set environment variable
        run: echo "BUILD_MODE=PRODUCTION" >> $GITHUB_ENV

      - name: Clean cache if needed
        if: ${{ inputs.clean_cache }}
        run: |
          rm -rf ~/.build
          rm -rf ~/.netrc

      - name: Cache SwiftPM dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.build
            .build
          key: ${{ runner.os }}-spm-test-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-test-

      - name: Cache netrc
        uses: actions/cache@v3
        with:
          path: ~/.netrc
          key: ${{ runner.os }}-netrc-test-${{ hashFiles('**/Package.resolved') }}

      - name: Setup SwiftPM Config
        run: |
          echo "machine github.com login oversizedev password ${{ secrets.ACTIONS_TOKEN }}" > ~/.netrc
          chmod 600 ~/.netrc
          set -euo pipefail
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.0.app && /usr/bin/xcodebuild -version
        
      - name: Run macOS tests
        run: swift test -v
