name: Tests

on:
  workflow_dispatch:
  workflow_call:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs: 

  test:
    name: Tests
    runs-on: macOS-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app && /usr/bin/xcodebuild -version
        
      - name: Run macOS tests
        run: swift test -v
